### ISSUE TITLE
backport 

### ISSUE THREAD

**Issue by fommil** [dwijnand/sbt-macro-bugs#1]
I'm not ready to give up yet on sbt 0.13.x support for macros: https://gitter.im/scala/contributors?at=5827daa931c5cbef43eb9b1e

> Jason Zaugg @retronym 03:14
> https://github.com/scala/scala/commit/6e4c926b4a4c5e8dd350ae3a150490a794b139ca in which after macro expansion, we discard the tree returned by the macro and leave the expandee in the AST (albeit with the type computed by the macro). That idea stemmed from my implementation of the same within the scala.async macro: https://github.com/scala/async/pull/46

**Comment by fommil** [comment]
the way to approach this could be to use https://github.com/fommil/sbt-scala-monkey and then when happy move to the ensime monkeys for the 2.10 build.

**Comment by dwijnand** [comment]
I've given up on 0.13.x by now. you?

**Comment by fommil** [comment]
I've given up on everything, man

**Comment by dwijnand** [comment]
lol
